name: Build clusters


on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build Insecure API cluster
        run: ansible-playbook insecure-port.yml