name: Build clusters


on:
  push:
    branches: [ main ]


jobs:
  build_2004:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build Insecure API cluster on 20.04
        run: ansible-playbook insecure-port.yml

  build_1804:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ansible on 18.04
        run: ./install_ansible_ubuntu.sh
      - name: Build Insecure API cluster on 18.04
        run: ansible-playbooks insecure-port.yml